[package]
name = "bytepack_derive"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.5"
quote = "1.0.2"
